group/api/urls.py
from django.urls import path
from django.urls import include
from rest_framework.routers import SimpleRouter

from api.views import TeacherViewSet, StudentViewSet, GroupViewSet

app_name = "api"

router = SimpleRouter()
router.register(r'teachers', TeacherViewSet)
router.register(r'students', StudentViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('', include((router.urls, "api"), namespace='api')),
    path('teacher-list/',
         TeacherViewSet.as_view({'get': 'list'}),
         name='teacher-list'),
    path('students-list/',
         StudentViewSet.as_view({'get': 'list'}),
         name='student-list'),
    path('groups-list/',
         GroupViewSet.as_view({'get': 'list'}),
         name='group-list'),
]

group/core/urls.py
from core.views import CreateGroupView, \
    CreateStudentView, \
    GroupView, \
    StudentView, \
    UpdateStudentView,\
    SendMailView,\
    RegistrationView, \
    TeacherAccountsView, \
    DownloadStudentList,\
    DownloadGroupList

from django.contrib.auth import views
from django.urls import path


app_name = "core"

urlpatterns = [
    path('group/create/', CreateGroupView.as_view(),
         name='create-group'),
    path('student/create/', CreateStudentView.as_view(),
         name='create-student'),
    path('student/update/<int:pk>', UpdateStudentView.as_view(),
         name='update-student'),
    path('student/list', StudentView.as_view(), name='students-list'),
    # path('student/delete/<int:pk>', DeleteStudentView.as_view(),
    #      name='delete-student'),
    path('registr/', RegistrationView.as_view(), name='registration-user'),
    path('send/mail/', SendMailView.as_view(), name='send-mail'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/user/', TeacherAccountsView.as_view(), name='account-user'),
    path('downnload/student/csv/',
         DownloadStudentList.as_view(),
         name='download-students-list'),
    path('downnload/group/csv/',
         DownloadGroupList.as_view(),
         name='download-group-list'),
    path('', GroupView.as_view(), name='home'),
]

group/group/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path("api/v1/", include('api.urls', 'api')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path("", include('core.urls', 'core')),
]

group/core/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class TeacherUser(AbstractUser):

    class Meta:
        verbose_name = 'Препод'
        verbose_name_plural = 'Преподы'

    def __str__(self):
        return self.first_name


class Group(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    teacher = models.ForeignKey(get_user_model(),
                                on_delete=models.CASCADE,
                                verbose_name='Препод',
                                related_name="teacher_groups")

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return f"{self.name} "


class Student(models.Model):
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255,
                                 verbose_name='Фамилия',
                                 null=True)
    phone = PhoneNumberField(null=False,)
    age = models.IntegerField(validators=[MinValueValidator(1),
                                          MaxValueValidator(100)],
                              verbose_name='Возраст')
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              verbose_name='Группа',
                              related_name='students')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return f"{self.first_name}, {self.group}"


class Logger(models.Model):
    path = models.CharField(max_length=255, verbose_name='Путь')
    method = models.CharField(max_length=255, verbose_name='Метод')
    logged_at = models.DateTimeField(auto_now_add=True,
                                     editable=False,
                                     verbose_name='Дата Сохранения')

    class Meta:
        verbose_name = 'Регистратор'
        verbose_name_plural = 'Регистраторы'

    def __str__(self):
        return self.path

group/core/forms.py
from core.models import Group, Student, TeacherUser
from django import forms


# class GroupCreateForm(forms.Form):
#     name = forms.CharField()
#     teacher = forms.ModelChoiceField(
#         queryset=TeacherModel.objects.all(),
#         widget=forms.widgets.RadioSelect()
#     )
#
#     def save(self):
#         track = GroupModel.objects.create(**self.cleaned_data)
#         return track


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'teacher': forms.widgets.RadioSelect()
        }


# class StudentCreateForm(forms.Form):
#     name = forms.CharField()
#     age = forms.IntegerField(max_value=80,
#                              min_value=17
#                              )
#     group = forms.ModelChoiceField(queryset=Teacher.objects.all(),
#                                    widget=forms.widgets.CheckboxInput()
#                                    )


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class ContactUSForm(forms.Form):
    title = forms.CharField()
    message = forms.CharField()
    email_from = forms.EmailField()


class RegistrationForm(forms.ModelForm):
    password_confirmation = forms.CharField(max_length=255,
                                            widget=forms.PasswordInput)

    class Meta:
        model = TeacherUser
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email',
                  'password',
                  'password_confirmation')

    def clean_password_confirmation(self):
        if self.cleaned_data['password'] !=\
                self.cleaned_data['password_confirmation']:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data['password']

    def save(self, commit=False):
        user = super(RegistrationForm, self).save(commit=True)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

group/core/views.py
# from django.contrib.auth import get_user_model
# from django.contrib.auth.decorators import login_required
import csv

from core.forms import GroupCreateForm,\
    StudentForm,\
    ContactUSForm,\
    RegistrationForm
from core.models import Group, Student
from core.tasks import send_mail_task

from django.db.models.aggregates import Avg, Count, Max, Min
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, \
    UpdateView, FormView, View
from django.template import loader


class GroupView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        groups = Group.objects.all().select_related()
        info_about_group = groups.annotate(
            student_count=Count('students'),
            avg_age=Avg('students__age'),
            min_age=Min('students__age'),
            max_age=Max('students__age')
        )
        context = {
            'info_about_group': info_about_group,
            'mas': [1, 2, 3, 4, 5],
            'some_str': 'Lorem ipsum',
            'groups': groups
        }
        return context


class CreateGroupView(CreateView):
    template_name = 'create.html'
    form_class = GroupCreateForm
    success_url = reverse_lazy('core:home')


class StudentView(TemplateView):
    template_name = 'students_list.html'

    def get_context_data(self, **kwargs):
        students = Student.objects.all().select_related()
        context = {
            'students': students
        }
        return context


class UpdateStudentView(UpdateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    form_class = StudentForm
    model = Student


class CreateStudentView(CreateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    form_class = StudentForm


# class DeleteStudentView(DeleteView):
#     model = Student
#     success_url = reverse_lazy('core:home')
#
#     def get_success_url(self):
#         return reverse_lazy('core:home')
#

class SendMailView(FormView):
    template_name = 'send_mail.html'
    success_url = reverse_lazy('core:home')
    form_class = ContactUSForm

    def form_valid(self, form):
        send_mail_task.delay(form.cleaned_data['title'],
                             form.cleaned_data['message'],
                             form.cleaned_data['email_from'])
        return super(SendMailView, self).form_valid(form)


class RegistrationView(CreateView):
    template_name = 'registration.html'
    success_url = reverse_lazy('core:home')
    form_class = RegistrationForm


class TeacherAccountsView(TemplateView):
    template_name = 'user_accounts.html'


class DownloadStudentList(View):

    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="students_list.csv"'  # noqa

        writer = csv.writer(response)
        writer.writerow(['first name', 'last name', 'phone', 'age', 'group'])
        for student in Student.objects.all():
            writer.writerow([student.first_name,
                             student.last_name,
                             student.phone,
                             student.age,
                             student.group])
        return response


class DownloadGroupList(View):

    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="group_list.csv"'  # noqa
        for group in Group.objects.all():
            name_group = group.name
            teacher_group = group.teacher
        csv_data = (
            ('Name', 'Teacher'),
            (name_group, teacher_group)
        )

        student_file = loader.get_template('group_list.txt')
        context = ({
            'data': csv_data,
        })
        print(context)
        response.write(student_file.render(context))
        return response

group/core/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

group/core/templates/create.html
{% extends 'base.html' %}
{% block title %}Create{% endblock %}
{%block content%}
    <div class="container-fluid main_section">
        <div class="container  ">
            <div class="row">
                 <form method="POST">{% csrf_token %}
                    {{form}}
                    <button type="submit" class="main_btn">Создать</button>
                </form>
            </div>
        </div>
    </div>
{%endblock%}

group/core/templates/index.html
{% extends 'base.html' %}
{% block title %}Main page{% endblock %}
{% load custom_tags_and_filter%}
{%block content%}
    <section class="container-fluid main_section ">
        <div class="container wrapper_table">
            <div class="row">
                    <h1 class="w-100">{{ mas|even_numb|join:", " }}</h1>
                    <h1 class="w-100">{{ some_str|count_words}}</h1>
                <div class="w-100 row">
                    {% if user.is_authenticated %}
                        <div>
                            <div class="color_blk">Пользователь: {{ user.first_name }}</div>
                        </div>
                        <div class="col-md-4 wrapper_btn">
                            <a href="{% url 'core:logout'%}" class="main_btn btn">Выход</a>
                         </div>
                    {% endif %}
                    {% if not user.is_authenticated %}
                         <div class="col-md-4 wrapper_btn">
                        <a href="{% url 'core:registration-user' %}" class="main_btn btn">Регистарция</a>
                        </div>
                        <div class="col-md-4 wrapper_btn">
                            <a href="{% url 'core:login' %}" class="main_btn btn">Вход</a>
                        </div>
                    {% endif %}
                </div>
                <h1 >Список групп</h1>
                <table class="w-100">
                    <tr>
                        <th>Название группы</th>
                        <th>Количество студентов</th>
                        <th>Средний возраст группы</th>
                        <th>Мин возраст</th>
                        <th>Макс возраст</th>
                        <th>Препод</th>
                    </tr>
                     {% for some_info in info_about_group %}
                        <tr>
                             <td>{{some_info.name}}</td>
                            <td>{{ some_info.student_count}}</td>
                            <td>{{ some_info.avg_age|default:"-"}}</td>
                            <td>{{ some_info.min_age|default:"-"}}</td>
                            <td>{{ some_info.max_age|default:"-"}}</td>
                            <td>{{ some_info.teacher }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:create-group' %}" class="main_btn btn">Добавить Группу</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:create-student' %}" class="main_btn btn">Добавить Студента</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:students-list'%}" class="main_btn btn">Список студентов</a>
                </div>
            </div>
            <div>
                {% random_teacher 5 %}
            </div>
             <div>
                 {% query_filter groups name='научная литература' as  filtered_groups %}
                 {% for group in filtered_groups  %}
                    <h1>{{ group.name }}</h1>
                 {% endfor %}
            </div>
            </div>
    </section>
{%endblock%}

group/core/templates/registration.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock %}
{%block content%}
    <div class="container-fluid main_section">
        <div class="container  ">
            <div class="row">
                 <form method="POST">{% csrf_token %}
                    {{form}}
                    <button type="submit" class="main_btn">Создать</button>
                </form>
            </div>
        </div>
    </div>
{%endblock%}

group/core/templates/send_mail.html
{% extends 'base.html' %}
{% block title %}Send mail{% endblock %}
{%block content%}
<section class="container-fluid main_section">
    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="form-group">
                  <button type="submit" class="main_btn">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{%endblock%}

group/core/templates/students_list.html
{% extends 'base.html' %}
{% block title %}Students list{% endblock %}
{% block content %}

<section class="container-fluid main_section ">
        <div class="container wrapper_table">
            <div class="row">
                <h1>Список студентов</h1>
                <table class="w-100">
                    <tr>
                        <th>№</th>
                        <th>Имя</th>
                        <th>Группа</th>
                        <th>Возраст</th>
                        <th>Телефон</th>
                        <th></th>
                        <th></th>
                    </tr>
                     {% for student in students %}
                        <tr>
                             <td>{{student.name}}</td>
                            <td>{{ student.last_name}}</td>
                            <td>{{ student.group}}</td>
                            <td>{{ student.age}}</td>
                            <td>{{ student.phone|default:'-'}}</td>
                            <td class="wrapper_btn"><a href="{% url 'core:update-student' student.id %}" class="main_btn btn">Изменить</a></td>
{#                            <td>#}
{#                                <form method="POST" action="{% url 'core:delete-student' student.id %}" class="">#}
{#                                    {% csrf_token %}<input type="submit" value="Удалить" class="main_btn">#}
{#                                 </form>#}
{#                            </td>#}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            </div>

    </section>
{%endblock%}

group/core/templates/teacher_table.html
<h1 >Список учителей</h1>
                <table class="w-100">
                    <tr>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th>Группа</th>
                    </tr>
                     {% for teacher in teachers %}
                        <tr>
                             <td>{{ teacher.first_name }}</td>
                            <td>{{ teacher.last_name}}</td>
                            <td>{{ teacher.teacher_groups.name|default:'-'}}</td>
                        </tr>
                    {% endfor %}
                </table>

group/core/templates/user_accounts.html
{% extends 'base.html' %}
{% block title %}Users page{% endblock %}
{%block content%}
{% if user.is_authenticated %}
<section class="container-fluid main_section">
    <div class="container">
        <div class="row">
            <div class="w-100 row">
                    <div>
                        <div class="color_blk">Пользователь: {{ user.first_name }}</div>
                    </div>
                    <div class="col-md-4 wrapper_btn">
                        <a href="{% url 'core:logout'%}" class="main_btn btn">Выход</a>
                     </div>
            </div>
            <h1 >Список груп</h1>
                <table class="w-100">
                    <tr>
                        <th>Название группы</th>
                        <th>Студенты</th>
                    </tr>

                     {% for group in user.teacher_groups.all %}
                        <tr>
                            <td>{{ group.name}}</td>
                                <td>{% for student in group.students.all %}
                                    {{ student.first_name }} {{ student.last_name }}<br>
                                    {% endfor %}
                                </td>
                        </tr>
                    {% endfor %}
                </table>
        </div>
    </div>
</section>
{% endif %}
{%endblock%}